#############################################################################
# Makefile for building: Delete_dubbel_files_qt_app
# Generated by qmake (3.1) (Qt 6.0.0)
# Project:  Delete_dubbel_files_qt_app.pro
# Template: app
# Command: /Users/leopoldmols/Documents/QT6.0/6.0.0/clang_64/bin/qmake -o Makefile Delete_dubbel_files_qt_app.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.15 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -Wall -pedantic-errors -std=c++17 -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.15 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers -I../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtGui.framework/Headers -I../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/macx-clang -F/Users/leopoldmols/Documents/QT6.0/6.0.0/clang_64/lib
QMAKE         = /Users/leopoldmols/Documents/QT6.0/6.0.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/leopoldmols/Documents/QT6.0/6.0.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/leopoldmols/Documents/QT6.0/6.0.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Delete_dubbel_files_qt_app1.0.0
DISTDIR = /Users/leopoldmols/Desktop/Programmes/Suppr_fichiers_finissant_par_espace_2/Delete_dubbel_files_qt_app/.tmp/Delete_dubbel_files_qt_app1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.15 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/leopoldmols/Documents/QT6.0/6.0.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/leopoldmols/Documents/QT6.0/6.0.0/clang_64/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		source.cpp 
OBJECTS       = main.o \
		source.o
DIST          = ../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/device_config.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/unix.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/mac.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/macx.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/sanitize.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/clang.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/qconfig.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_ext_freetype.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_ext_libpng.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core5compat.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core_qobject_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_linguist.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_shadertools.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qt_config.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/toolchain.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/default_pre.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/default_post.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/warn_on.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qt.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/resources_functions.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/resources.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/moc.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/uic.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/file_copies.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/exceptions.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/yacc.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/lex.prf \
		Delete_dubbel_files_qt_app.pro header.h main.cpp \
		source.cpp
QMAKE_TARGET  = Delete_dubbel_files_qt_app
DESTDIR       = 
TARGET        = Delete_dubbel_files_qt_app

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/leopoldmols/Desktop/Programmes/Suppr_fichiers_finissant_par_espace_2/Delete_dubbel_files_qt_app/Delete_dubbel_files_qt_app.pro


include /Users/leopoldmols/Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Delete_dubbel_files_qt_app:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Delete_dubbel_files_qt_app.pro ../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/device_config.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/unix.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/mac.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/macx.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/sanitize.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/clang.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/qconfig.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_ext_freetype.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_ext_libpng.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core5compat.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core_qobject_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_linguist.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_shadertools.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qt_config.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/toolchain.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/default_pre.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/default_post.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/warn_on.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qt.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/resources_functions.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/resources.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/moc.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/uic.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/file_copies.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/exceptions.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/yacc.prf \
		../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/lex.prf \
		Delete_dubbel_files_qt_app.pro \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile Delete_dubbel_files_qt_app.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/spec_pre.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/device_config.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/unix.conf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/mac.conf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/macx.conf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/sanitize.conf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/gcc-base.conf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/clang.conf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/common/clang-mac.conf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/qconfig.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_ext_freetype.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_ext_libpng.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core5compat.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core5compat_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_core_qobject_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_linguist.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_linguist_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3d.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_shadertools.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_shadertools_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_tools_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qt_functions.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qt_config.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/toolchain.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/toolchain.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/default_pre.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/resolve_config.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/default_post.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qml_debug.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/mac.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/warn_on.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qt.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/resources_functions.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/resources.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/moc.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/uic.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/unix/thread.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/qmake_use.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/file_copies.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/rez.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/exceptions.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/yacc.prf:
../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/lex.prf:
Delete_dubbel_files_qt_app.pro:
../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Delete_dubbel_files_qt_app.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile Delete_dubbel_files_qt_app

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents header.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp source.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Delete_dubbel_files_qt_app_fr_BE.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -Wall -pedantic-errors -std=c++17 -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.15 -Wall -Wextra -dM -E -o moc_predefs.h ../../../../Documents/QT6.0/6.0.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp header.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtCore.framework/Headers/QBuffer \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtCore.framework/Headers/qbuffer.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

source.o: source.cpp header.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtCore.framework/Headers/QBuffer \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtCore.framework/Headers/qbuffer.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../../../Documents/QT6.0/6.0.0/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o source.o source.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Delete_dubbel_files_qt_app/bin || mkdir -p $(INSTALL_ROOT)/opt/Delete_dubbel_files_qt_app/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Delete_dubbel_files_qt_app/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Delete_dubbel_files_qt_app/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Delete_dubbel_files_qt_app/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

